/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * The Fourier Synthesizer web component is an interactive waveform and sound generator based on Fourier synthesis.
     * ## Layout
     * The size of the synthesizer will by default be as large as possible within the web page. You can use CSS width and height properties and/or page layout to control the size if necessary.
     * ```html
     * <fourier-synth style="width: 800px;"></fourier-synth>
     * ```
     */
    interface FourierSynth {
        /**
          * Text for the enable audio control label.
         */
        "audioLabel": string;
        /**
          * Automatically adjust the gain and DC offset (cos0) to match the wave. This doubles computational effort and therefore impacts performance by ~50%.
         */
        "autoAdjust": boolean;
        /**
          * Text for the auto adjust control label.
         */
        "autoAdjustLabel": string;
        /**
          * Color of graph background lines and dots. Use a CSS color value.
         */
        "axesColor": string;
        /**
          * Background color of graph. Use a CSS color value.
         */
        "backgroundColor": string;
        /**
          * Text for the cosine control prefix.
         */
        "cosPrefix": string;
        /**
          * Title text for the cosine controls.  Set text empty to hide the title.
         */
        "cosTitle": string;
        /**
          * Text for the DC (cos0) control label. HTML can be used e.g. `A<sub>0</sub>`.
         */
        "dcLabel": string;
        /**
          * Text for the dividers display control label. Set the text empty to hide the control.
         */
        "dividersLabel": string;
        /**
          * Text for the endpoints display control label. Set the text empty to hide the control.
         */
        "endpointsLabel": string;
        /**
          * The fundamental frequency of the fourier wave.
         */
        "fundamental": number;
        /**
          * Text for the fundamental control label. Set the text empty to hide the control.
         */
        "fundamentalLabel": string;
        /**
          * Text for the gain control label.
         */
        "gainLabel": string;
        /**
          * Text for the graph display control label.
         */
        "graphLabel": string;
        /**
          * Text for the grid dots display control label. Set the text empty to hide the control.
         */
        "gridDotsLabel": string;
        /**
          * Number of harmonics to control and produce.
         */
        "harmonics": number;
        /**
          * Text for the harmonics control label. Set the text empty to hide the control.
         */
        "harmonicsLabel": string;
        /**
          * Don't display the fundamental wave divider lines.
         */
        "hideDividers": boolean;
        /**
          * Don't display the fundamental wave endpoint dots.
         */
        "hideEndpoints": boolean;
        /**
          * Don't display the graph.
         */
        "hideGraph": boolean;
        /**
          * Don't display the graph background dots.
         */
        "hideGridDots": boolean;
        /**
          * Don't display the graph DC offset line.
         */
        "hideOffset": boolean;
        /**
          * Color of the waveform plot line. Use a CSS color value.
         */
        "lineColor": string;
        /**
          * The width of the waveform plot line.
         */
        "lineWidth": number;
        /**
          * Text for the line width control label. Set the text empty to hide the control.
         */
        "lineWidthLabel": string;
        /**
          * Text for the main title. Set the text empty to hide the title.
         */
        "mainTitle": string;
        /**
          * Limit of the number of harmonics. The actual highest possible number of harmonics is based on the frequency. The highest possible harmonic frequency is 20000Hz. At the lowest fundamental 20Hz there can therefore be up to 1000 harmonics. High values can crash, hang, or otherwise bring the browser to a halt. USE WITH CAUTION.
         */
        "maxHarmonics": number;
        /**
          * Color of the graph DC offset line and waveform endpoint dots. Use a CSS color value.
         */
        "offsetColor": string;
        /**
          * Text for the offset display control label. Set the text empty to hide the control.
         */
        "offsetLabel": string;
        /**
          * Number of fundamental wave periods to display in the graph. From 1 to 5.
         */
        "periods": number;
        /**
          * Text for the periods control label. Set the text empty to hide the control.
         */
        "periodsLabel": string;
        /**
          * Text for the reset button.
         */
        "resetText": string;
        /**
          * Text for the sine control prefix.
         */
        "sinPrefix": string;
        /**
          * Title text for the sine controls. Set text empty to hide the title.
         */
        "sinTitle": string;
    }
}
declare global {
    /**
     * The Fourier Synthesizer web component is an interactive waveform and sound generator based on Fourier synthesis.
     * ## Layout
     * The size of the synthesizer will by default be as large as possible within the web page. You can use CSS width and height properties and/or page layout to control the size if necessary.
     * ```html
     * <fourier-synth style="width: 800px;"></fourier-synth>
     * ```
     */
    interface HTMLFourierSynthElement extends Components.FourierSynth, HTMLStencilElement {
    }
    var HTMLFourierSynthElement: {
        prototype: HTMLFourierSynthElement;
        new (): HTMLFourierSynthElement;
    };
    interface HTMLElementTagNameMap {
        "fourier-synth": HTMLFourierSynthElement;
    }
}
declare namespace LocalJSX {
    /**
     * The Fourier Synthesizer web component is an interactive waveform and sound generator based on Fourier synthesis.
     * ## Layout
     * The size of the synthesizer will by default be as large as possible within the web page. You can use CSS width and height properties and/or page layout to control the size if necessary.
     * ```html
     * <fourier-synth style="width: 800px;"></fourier-synth>
     * ```
     */
    interface FourierSynth {
        /**
          * Text for the enable audio control label.
         */
        "audioLabel"?: string;
        /**
          * Automatically adjust the gain and DC offset (cos0) to match the wave. This doubles computational effort and therefore impacts performance by ~50%.
         */
        "autoAdjust"?: boolean;
        /**
          * Text for the auto adjust control label.
         */
        "autoAdjustLabel"?: string;
        /**
          * Color of graph background lines and dots. Use a CSS color value.
         */
        "axesColor"?: string;
        /**
          * Background color of graph. Use a CSS color value.
         */
        "backgroundColor"?: string;
        /**
          * Text for the cosine control prefix.
         */
        "cosPrefix"?: string;
        /**
          * Title text for the cosine controls.  Set text empty to hide the title.
         */
        "cosTitle"?: string;
        /**
          * Text for the DC (cos0) control label. HTML can be used e.g. `A<sub>0</sub>`.
         */
        "dcLabel"?: string;
        /**
          * Text for the dividers display control label. Set the text empty to hide the control.
         */
        "dividersLabel"?: string;
        /**
          * Text for the endpoints display control label. Set the text empty to hide the control.
         */
        "endpointsLabel"?: string;
        /**
          * The fundamental frequency of the fourier wave.
         */
        "fundamental"?: number;
        /**
          * Text for the fundamental control label. Set the text empty to hide the control.
         */
        "fundamentalLabel"?: string;
        /**
          * Text for the gain control label.
         */
        "gainLabel"?: string;
        /**
          * Text for the graph display control label.
         */
        "graphLabel"?: string;
        /**
          * Text for the grid dots display control label. Set the text empty to hide the control.
         */
        "gridDotsLabel"?: string;
        /**
          * Number of harmonics to control and produce.
         */
        "harmonics"?: number;
        /**
          * Text for the harmonics control label. Set the text empty to hide the control.
         */
        "harmonicsLabel"?: string;
        /**
          * Don't display the fundamental wave divider lines.
         */
        "hideDividers"?: boolean;
        /**
          * Don't display the fundamental wave endpoint dots.
         */
        "hideEndpoints"?: boolean;
        /**
          * Don't display the graph.
         */
        "hideGraph"?: boolean;
        /**
          * Don't display the graph background dots.
         */
        "hideGridDots"?: boolean;
        /**
          * Don't display the graph DC offset line.
         */
        "hideOffset"?: boolean;
        /**
          * Color of the waveform plot line. Use a CSS color value.
         */
        "lineColor"?: string;
        /**
          * The width of the waveform plot line.
         */
        "lineWidth"?: number;
        /**
          * Text for the line width control label. Set the text empty to hide the control.
         */
        "lineWidthLabel"?: string;
        /**
          * Text for the main title. Set the text empty to hide the title.
         */
        "mainTitle"?: string;
        /**
          * Limit of the number of harmonics. The actual highest possible number of harmonics is based on the frequency. The highest possible harmonic frequency is 20000Hz. At the lowest fundamental 20Hz there can therefore be up to 1000 harmonics. High values can crash, hang, or otherwise bring the browser to a halt. USE WITH CAUTION.
         */
        "maxHarmonics"?: number;
        /**
          * Color of the graph DC offset line and waveform endpoint dots. Use a CSS color value.
         */
        "offsetColor"?: string;
        /**
          * Text for the offset display control label. Set the text empty to hide the control.
         */
        "offsetLabel"?: string;
        /**
          * Number of fundamental wave periods to display in the graph. From 1 to 5.
         */
        "periods"?: number;
        /**
          * Text for the periods control label. Set the text empty to hide the control.
         */
        "periodsLabel"?: string;
        /**
          * Text for the reset button.
         */
        "resetText"?: string;
        /**
          * Text for the sine control prefix.
         */
        "sinPrefix"?: string;
        /**
          * Title text for the sine controls. Set text empty to hide the title.
         */
        "sinTitle"?: string;
    }
    interface IntrinsicElements {
        "fourier-synth": FourierSynth;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * The Fourier Synthesizer web component is an interactive waveform and sound generator based on Fourier synthesis.
             * ## Layout
             * The size of the synthesizer will by default be as large as possible within the web page. You can use CSS width and height properties and/or page layout to control the size if necessary.
             * ```html
             * <fourier-synth style="width: 800px;"></fourier-synth>
             * ```
             */
            "fourier-synth": LocalJSX.FourierSynth & JSXBase.HTMLAttributes<HTMLFourierSynthElement>;
        }
    }
}
